### ISSUE TITLE
Changing Bluemix Service

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/XPages-Fusion-Application#10]
Language Translation service is being deprecated and replaced by Language Translator service. Are there any changes required for the "Deploy to Bluemix" functionality to continue to work after the Language Translation service is withdrawn on 1st November?

**Comment by briangleeson** [comment]
Well, doh, I totally missed this issue until now! You were correct, and there was a small change needed in the deploy to bluemix funcitonality and in the Java code of the NSF itself, after the update in November. I've updated everything in my latest PR so everything is back in action now. Apologies for missing this for so long
